# Feature Analysis

In [1]:
# import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load data (extended)
df_extended = pd.read_csv('../data/featureDf_extended.csv')

# keep only features cols
df_extended.drop(['processing_status', 'error_message'], axis=1, inplace=True)

print('='*60)
print('no. cols')
print('='*60)

============================================================
no. cols
============================================================

In [3]:
df_extended

,img_id,hsv_mean_h,hsv_mean_s,hsv_mean_v,hsv_std_h,hsv_std_s,hsv_std_v,sp_hsv_std_h,sp_hsv_std_s,sp_hsv_std_v,rel_hsv_diff_h,rel_hsv_diff_s,rel_hsv_diff_v,symmetry,border,diameter
0,PAT_1516_1765_530.png,0.596813,0.721711,0.562222,0.006292,0.074530,0.049364,0.006275,0.081927,0.049157,0.009938,0.188584,0.083688,0.738506,0.776982,0.859504
1,PAT_46_881_939.png,0.744147,0.143894,0.699154,0.054320,0.035045,0.034500,0.050205,0.032393,0.032636,0.060345,0.025761,0.013930,0.734336,0.579152,0.960274
2,PAT_1545_1867_547.png,0.705389,0.169257,0.919523,0.035141,0.018431,0.069164,0.034673,0.019034,0.068287,0.008902,0.016126,0.025334,0.680112,0.625163,1.000000
3,PAT_1989_4061_934.png,0.646455,0.214990,0.608748,0.027248,0.064702,0.029728,0.026081,0.063807,0.030374,0.034895,0.020770,0.000674,0.690998,0.779322,0.979094
4,PAT_684_1302_588.png,0.669913,0.396890,0.527158,0.015138,0.058925,0.036768,0.015137,0.059403,0.033457,0.027128,0.050080,0.010655,0.881281,0.832370,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,PAT_386_785_536.png,0.572169,0.361423,0.512538,0.035448,0.094249,0.134673,0.031277,0.080017,0.125176,0.052471,0.063358,0.132031,0.765386,0.813212,0.948387
1941,PAT_273_421_905.png,0.650176,0.628007,0.647141,0.010064,0.063317,0.062950,0.009124,0.056237,0.056508,0.006131,0.000052,0.006018,0.895364,0.862230,1.000000
1942,PAT_491_934_46.png,0.632516,0.387129,0.773343,0.014211,0.082124,0.056153,0.012397,0.074813,0.048381,0.012684,0.012868,0.023426,0.920479,0.874997,1.000000
1943,PAT_46_880_140.png,0.709280,0.166227,0.738225,0.041577,0.016758,0.054453,0.032534,0.013777,0.054036,0.032230,0.000832,0.002045,0.788334,0.773051,0.986352
1944,PAT_326_690_823.png,0.662955,0.382170,0.700245,0.020406,0.105157,0.032953,0.021432,0.105454,0.031144,0.022301,0.096489,0.019026,0.898760,0.849816,1.000000

In [4]:
df_extended.isna().sum()

img_id            0
hsv_mean_h        0
hsv_mean_s        0
hsv_mean_v        0
hsv_std_h         0
hsv_std_s         0
hsv_std_v         0
sp_hsv_std_h      2
sp_hsv_std_s      2
sp_hsv_std_v      2
rel_hsv_diff_h    0
rel_hsv_diff_s    0
rel_hsv_diff_v    0
symmetry          0
border            0
diameter          0
dtype: int64

In [5]:
df_extended

,img_id,hsv_mean_h,hsv_mean_s,hsv_mean_v,hsv_std_h,hsv_std_s,hsv_std_v,sp_hsv_std_h,sp_hsv_std_s,sp_hsv_std_v,rel_hsv_diff_h,rel_hsv_diff_s,rel_hsv_diff_v,symmetry,border,diameter
0,PAT_1516_1765_530.png,0.596813,0.721711,0.562222,0.006292,0.074530,0.049364,0.006275,0.081927,0.049157,0.009938,0.188584,0.083688,0.738506,0.776982,0.859504
1,PAT_46_881_939.png,0.744147,0.143894,0.699154,0.054320,0.035045,0.034500,0.050205,0.032393,0.032636,0.060345,0.025761,0.013930,0.734336,0.579152,0.960274
2,PAT_1545_1867_547.png,0.705389,0.169257,0.919523,0.035141,0.018431,0.069164,0.034673,0.019034,0.068287,0.008902,0.016126,0.025334,0.680112,0.625163,1.000000
3,PAT_1989_4061_934.png,0.646455,0.214990,0.608748,0.027248,0.064702,0.029728,0.026081,0.063807,0.030374,0.034895,0.020770,0.000674,0.690998,0.779322,0.979094
4,PAT_684_1302_588.png,0.669913,0.396890,0.527158,0.015138,0.058925,0.036768,0.015137,0.059403,0.033457,0.027128,0.050080,0.010655,0.881281,0.832370,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,PAT_386_785_536.png,0.572169,0.361423,0.512538,0.035448,0.094249,0.134673,0.031277,0.080017,0.125176,0.052471,0.063358,0.132031,0.765386,0.813212,0.948387
1941,PAT_273_421_905.png,0.650176,0.628007,0.647141,0.010064,0.063317,0.062950,0.009124,0.056237,0.056508,0.006131,0.000052,0.006018,0.895364,0.862230,1.000000
1942,PAT_491_934_46.png,0.632516,0.387129,0.773343,0.014211,0.082124,0.056153,0.012397,0.074813,0.048381,0.012684,0.012868,0.023426,0.920479,0.874997,1.000000
1943,PAT_46_880_140.png,0.709280,0.166227,0.738225,0.041577,0.016758,0.054453,0.032534,0.013777,0.054036,0.032230,0.000832,0.002045,0.788334,0.773051,0.986352
1944,PAT_326_690_823.png,0.662955,0.382170,0.700245,0.020406,0.105157,0.032953,0.021432,0.105454,0.031144,0.022301,0.096489,0.019026,0.898760,0.849816,1.000000